<?php

use Nette\Application\Routers\Route;
use Nette\Application\Routers\RouteList;
use Nette\Application\Routers\SimpleRouter;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

$application = \Nette\Environment::getApplication();
$application->errorPresenter = 'Front:Error';
$application->catchExceptions = \Nette\Environment::isProduction();

// Setup router using mod_rewrite detection
//if (function_exists('apache_get_modules') && in_array('mod_rewrite', apache_get_modules())) {
	$container->router[] = new Route('index.php', 'Front:Homepage:default', Route::ONE_WAY);

	$container->router[] = $adminRouter = new RouteList('Admin');
	$adminRouter[] = new Route('admin/<presenter>/<action>', 'Homepage:default');

	$container->router[] = $frontRouter = new RouteList('Front');
	$frontRouter[] = new Route('fotogalerie-2013/', 'Homepage:fotogalerie2013');
	$frontRouter[] = new Route('<action>/<recnik>/', 'Homepage:recnici');
	$frontRouter[] = new Route('festival/', 'Homepage:festival');
    $frontRouter[] = new Route('konference/', 'Homepage:predprogram');
    $frontRouter[] = new Route('detailni-program/', 'Homepage:program');
    $frontRouter[] = new Route('<action>/[<id>]', 'Homepage:default');
	$frontRouter[] = new Route('<presenter>/<action>[/<id>]', 'Homepage:default');
//}
return $container;
